insert into pizza (name,description,price) values ('Margherita','pomodoro e mozzarella', 8)
insert into pizza (name,description,price) values('Marinara','pomodoro e aglio', 10)
insert into offer (start_date,expire_date,title,pizza_id) values ('2023-12-05','2023-12-09', 'special offer a', 1)
insert into ingredients (name) values ('cheese')
insert into ingredients (name) values ('tomato')
insert into ingredients (name) values ('onion')